import {test,expect} from '@playwright/test';
test('banker desktop dashboard renders, filters work and page contains no assistant branding',async({page})=>{
 const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto('/');await expect(page.getByRole('heading',{name:'Tổng quan',exact:true})).toBeVisible();await expect(page.locator('.loan-title').first()).toBeVisible();await page.screenshot({path:'/workspace/lendinghub/.data/screenshots/desktop.png',fullPage:true});await page.getByRole('textbox',{name:'Tìm hồ sơ'}).fill('Nhà máy');await expect(page.locator('.loan-title')).toHaveCount(1);await page.getByRole('button',{name:'Bộ lọc',exact:true}).click();await page.getByLabel('Đối tượng',{exact:true}).selectOption('PER');await expect(page.getByText('Không có hồ sơ phù hợp')).toBeVisible();expect(errors).toEqual([]);await expect(page.locator('body')).not.toContainText(/ChatGPT|Codex/i);
});
test('full loan workflow is operable through the UI',async({page,request})=>{
 const users=await (await request.get('/api/demo/users')).json();const com=users.find(u=>u.role==='COM'),bar=users.find(u=>u.role==='BAR');
 await page.goto('/');await expect(page.locator('.loan-title').first()).toBeVisible();
 const switchTo=async u=>{await page.getByLabel('Chọn tài khoản trải nghiệm').selectOption(u.id);await expect(page.locator('.loading')).toHaveCount(0);};
 const open=async()=>{await page.locator('.sidebar nav').getByRole('button',{name:/Hồ sơ của tôi|Khám phá hồ sơ/}).click();await page.getByRole('button',{name:'Quy trình thử trình duyệt',exact:true}).click();};
 await switchTo(com);await page.getByRole('button',{name:'Tạo hồ sơ vay'}).click();let modal=page.getByRole('dialog',{name:'Tạo hồ sơ vay'});await modal.getByLabel('Tên hồ sơ',{exact:true}).fill('Quy trình thử trình duyệt');await modal.locator('input[name="consent"]').check();await modal.getByRole('button',{name:'Tạo hồ sơ',exact:true}).click();await expect(page.getByRole('dialog',{name:'Chi tiết hồ sơ'})).toBeVisible();await page.getByRole('dialog',{name:'Chi tiết hồ sơ'}).getByRole('button',{name:'Đóng',exact:true}).click();
 await switchTo(bar);await open();await page.getByRole('button',{name:'Gửi đề xuất tài trợ',exact:true}).click();modal=page.getByRole('dialog',{name:'Gửi đề xuất tài trợ'});await modal.locator('input[name="simulate_deposit"]').check();await modal.getByRole('button',{name:'Gửi đề xuất & mô phỏng cọc'}).click();await expect(modal).not.toBeVisible();await page.getByRole('dialog',{name:'Chi tiết hồ sơ'}).getByRole('button',{name:'Đóng',exact:true}).click();
 await switchTo(com);await open();await page.getByRole('button',{name:'So sánh & chọn đề xuất'}).click();await page.getByRole('button',{name:'Chọn đề xuất này'}).click();modal=page.getByRole('dialog',{name:'Xác nhận lựa chọn banker'});await modal.locator('input[name="consent"]').check();await modal.getByRole('button',{name:'Xác nhận lựa chọn',exact:true}).click();await expect(modal).not.toBeVisible();await page.getByRole('button',{name:'Xác nhận điều khoản & bắt đầu'}).click();modal=page.getByRole('dialog',{name:'Điều khoản & bắt đầu xử lý'});await modal.locator('input[name="accept_terms"]').check();await modal.getByRole('button',{name:'Chấp thuận & bắt đầu mô phỏng'}).click();await expect(modal).not.toBeVisible();await page.getByRole('dialog',{name:'Chi tiết hồ sơ'}).getByRole('button',{name:'Đóng',exact:true}).click();
 await switchTo(bar);await open();await page.getByRole('button',{name:'Cập nhật tiến độ',exact:true}).click();modal=page.getByRole('dialog',{name:'Cập nhật tiến độ'});await modal.getByLabel('Mốc xử lý').selectOption('approved');await modal.getByLabel('Nội dung cập nhật').fill('Đã phê duyệt hồ sơ trải nghiệm.');await modal.getByRole('button',{name:'Xác nhận',exact:true}).click();await expect(modal).not.toBeVisible();await page.getByRole('button',{name:'Đặt lịch ký hợp đồng',exact:true}).click();modal=page.getByRole('dialog',{name:'Đặt lịch ký hợp đồng'});const future=new Date(Date.now()+86400000);await modal.locator('input[name="scheduled_at"]').fill(future.toISOString().slice(0,16));await modal.getByLabel('Địa điểm ký hợp đồng').fill('Phòng giao dịch mẫu');await modal.getByRole('button',{name:'Xác nhận',exact:true}).click();await expect(modal).not.toBeVisible();await page.getByRole('dialog',{name:'Chi tiết hồ sơ'}).getByRole('button',{name:'Đóng',exact:true}).click();
 await switchTo(com);await open();await page.getByRole('button',{name:'Tiến độ & lịch hẹn',exact:true}).click();await page.getByRole('button',{name:'Xác nhận lịch',exact:true}).click();await expect(page.getByText('Khách hàng đã xác nhận lịch hẹn.')).toBeVisible();await page.getByRole('dialog',{name:'Chi tiết hồ sơ'}).getByRole('button',{name:'Đóng',exact:true}).click();
 await switchTo(bar);await open();await page.getByRole('button',{name:'Báo đã giải ngân',exact:true}).click();modal=page.getByRole('dialog',{name:'Xác nhận báo giải ngân'});await modal.locator('input[name="confirm"]').check();await modal.getByRole('button',{name:'Xác nhận',exact:true}).click();await expect(modal).not.toBeVisible();await page.getByRole('dialog',{name:'Chi tiết hồ sơ'}).getByRole('button',{name:'Đóng',exact:true}).click();
 await switchTo(com);await open();await page.getByRole('button',{name:'Xác nhận nhận vốn & hoàn tất'}).click();modal=page.getByRole('dialog',{name:'Xác nhận nhận vốn & hoàn tất'});await modal.locator('input[name="confirm_received"]').check();await modal.getByRole('button',{name:'Xác nhận & hoàn tất'}).click();await expect(modal).not.toBeVisible();await page.getByRole('button',{name:'Tiến độ & lịch hẹn',exact:true}).click();await expect(page.getByRole('heading',{name:'Hành trình tài trợ đã hoàn tất'})).toBeVisible();await page.reload();await page.getByRole('button',{name:'Hồ sơ của tôi',exact:true}).click();await expect(page.getByRole('button',{name:'Quy trình thử trình duyệt',exact:true})).toBeVisible();
});
test('mobile layout fits and navigation opens',async({page})=>{await page.setViewportSize({width:390,height:844});await page.goto('/');await expect(page.locator('.loan-title').first()).toBeVisible();expect(await page.evaluate(()=>document.documentElement.scrollWidth)).toBeLessThanOrEqual(390);await page.screenshot({path:'/workspace/lendinghub/.data/screenshots/mobile.png',fullPage:true});await page.getByRole('button',{name:'Mở menu'}).click();await expect(page.locator('.sidebar')).toHaveClass(/open/);await page.getByRole('button',{name:'Gói vay',exact:true}).click();await expect(page.getByRole('heading',{name:'Giải pháp vốn từ đối tác'})).toBeVisible();});
test('admin audit and account creation screens are functional',async({page,request})=>{const users=await (await request.get('/api/demo/users')).json();await page.goto('/');await expect(page.locator('.loan-title').first()).toBeVisible();await page.getByLabel('Chọn tài khoản trải nghiệm').selectOption(users.find(u=>u.role==='ADMIN').id);await expect(page.locator('.loading')).toHaveCount(0);await page.getByRole('button',{name:'Quản trị hệ thống',exact:true}).click();await page.getByRole('button',{name:'Nhật ký hoạt động',exact:true}).click();await expect(page.locator('.audit-list>div').first()).toBeVisible();await page.getByRole('button',{name:'Tạo tài khoản trải nghiệm',exact:true}).click();const modal=page.getByRole('dialog',{name:'Tạo tài khoản trải nghiệm'});await modal.getByLabel('Loại tài khoản').selectOption('BRO');await modal.getByRole('button',{name:'Tạo tài khoản mẫu'}).click();await expect(modal).not.toBeVisible();await expect(page.locator('.sidebar-profile strong')).toContainText('BRO-');});
