import {test,before,after} from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,rmSync} from 'node:fs';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createDatabase,seed,createUser,transaction} from '../server/database.js';
import {createApp} from '../server/app.js';
let db,server,url,users,dir;
before(async()=>{dir=mkdtempSync(join(tmpdir(),'lending-tests-'));db=createDatabase(join(dir,'db.sqlite'));seed(db);users=db.prepare('SELECT * FROM users').all();server=createApp(db,{uploadDir:join(dir,'.data','uploads'),distDir:join(dir,'none')}).listen(0,'127.0.0.1');await new Promise(r=>server.once('listening',r));url=`http://127.0.0.1:${server.address().port}`;});
after(async()=>{if(server)await new Promise(r=>server.close(r));db?.close();rmSync(dir,{recursive:true,force:true});});
const byRole=r=>users.find(u=>u.role===r);
async function request(path,{user=byRole('COM'),method='GET',body,status=200}={}){const headers={};if(user)headers['x-demo-user']=user.id;if(body&&!(body instanceof FormData))headers['Content-Type']='application/json';const response=await fetch(url+'/api'+path,{method,headers,body:body instanceof FormData?body:body?JSON.stringify(body):undefined});assert.equal(response.status,status,await (response.status===status?Promise.resolve(''):response.text()));return response.headers.get('content-type')?.includes('application/json')?response.json():response;}
const loanData={borrower_type:'COM',title:'Hồ sơ kiểm thử',amount:3000000000,term:24,purpose:'Vốn lưu động',industry:'Sản xuất',location:'Hà Nội',revenue:12000000000,collateral:'Bất động sản',description:'Nhu cầu vốn kiểm thử tích hợp.',consent:true,private_data:{legalName:'Công ty mẫu',contact:'Liên hệ mẫu',phone:'0900000000',email:'sample@example.com',taxCode:'demo'}};
const proposalData={rate:8.5,fee:3000000,fee_description:'Phí công bố',days:10,conditions:'Thẩm định tài sản',simulate_deposit:true};
async function newLoan(user=byRole('COM')){return request('/loans',{method:'POST',body:loanData,user,status:201});}
test('health verifies database and explicitly identifies demo mode',async()=>{const v=await request('/health',{user:null});assert.equal(v.database,1);assert.equal(v.mode,'demo');});
test('identity and role checks reject absent, unknown and inappropriate identities',async()=>{await request('/loans',{user:null,status:401});await request('/loans',{user:{id:'unknown'},status:401});await request('/admin',{status:403});await request('/loans',{user:byRole('BAR'),method:'POST',body:loanData,status:403});await request('/demo/users',{user:null,method:'POST',body:{role:'ADMIN'},status:400});});
test('random aliases are unique within role and follow requested range',async()=>{const generated=Array.from({length:100},()=>createUser(db,'BRO'));assert.equal(new Set(generated.map(u=>u.alias)).size,100);for(const u of generated){assert.match(u.alias,/^BRO-\d{3,4}$/);assert.ok(Number(u.alias.slice(4))>=1&&Number(u.alias.slice(4))<=9999);}});
test('validations reject negative amounts, missing consent and mismatched borrower types',async()=>{await request('/loans',{method:'POST',body:{...loanData,amount:-1},status:400});await request('/loans',{method:'POST',body:{...loanData,consent:false},status:400});await request('/loans',{user:byRole('PER'),method:'POST',body:loanData,status:400});});
test('private identity and files are hidden from feed and unselected bankers',async()=>{const l=await newLoan();const publicList=await request('/loans',{user:byRole('BAR')});const v=publicList.find(x=>x.id===l.id);assert.ok(!('private_data' in v));assert.ok(!('owner_id' in v));const d=await request('/loans/'+l.id,{user:byRole('BAR')});assert.ok(!d.private_data);assert.deepEqual(d.documents,[]);const other=users.filter(u=>u.role==='COM')[1];await request('/loans/'+l.id,{user:other,status:403});});
test('document upload validates type, preserves private access and permits owner download',async()=>{const l=await newLoan();const form=new FormData();form.append('file',new Blob(['%PDF-1.4\nSample document\n%%EOF'],{type:'application/pdf'}),'sample.pdf');const d=await request('/loans/'+l.id+'/documents',{method:'POST',body:form,status:201});const response=await request('/documents/'+d.id);assert.ok((await response.text()).startsWith('%PDF-'));await request('/documents/'+d.id,{user:byRole('BAR'),status:403});const spoof=new FormData();spoof.append('file',new Blob(['not a pdf'],{type:'application/pdf'}),'fake.pdf');await request('/loans/'+l.id+'/documents',{method:'POST',body:spoof,status:400});});
test('oversize document uploads are rejected',async()=>{const l=await newLoan();const form=new FormData();form.append('file',new Blob([new Uint8Array(11*1024*1024)],{type:'application/pdf'}),'large.pdf');await request('/loans/'+l.id+'/documents',{method:'POST',body:form,status:400});});
test('multiple offers, selection, privacy, signing, progress, appointment and settlement work end to end',async()=>{
 const com=byRole('COM'),bankers=users.filter(u=>u.role==='BAR'),l=await newLoan();
 await request(`/loans/${l.id}/complete`,{method:'POST',body:{confirm_received:true,simulate_payment:true},status:409});
 await request(`/loans/${l.id}/proposals`,{user:bankers[0],method:'POST',body:proposalData,status:201});
 await request(`/loans/${l.id}/proposals`,{user:bankers[0],method:'POST',body:proposalData,status:409});
 await request(`/loans/${l.id}/proposals`,{user:bankers[1],method:'POST',body:{...proposalData,rate:9},status:201});
 let current=await request('/loans/'+l.id);assert.equal(current.proposals.length,2);
 const chosen=current.proposals.find(p=>p.banker_id===bankers[0].id);
 await request(`/loans/${l.id}/select`,{method:'POST',body:{proposal_id:chosen.id,consent:true}});
 current=await request('/loans/'+l.id,{user:bankers[0]});assert.equal(current.private_data.legalName,loanData.private_data.legalName);
 await request('/loans/'+l.id,{user:bankers[1],status:403});
 assert.equal(db.prepare("SELECT state FROM ledger WHERE loan_id=? AND user_id=?").get(l.id,bankers[1].id).state,'refunded_simulated');
 await request(`/loans/${l.id}/select`,{method:'POST',body:{proposal_id:chosen.id,consent:true},status:409});
 await request(`/loans/${l.id}/activate`,{method:'POST',body:{accept_terms:true,simulate_signature:true,simulate_deposit:true}});
 await request(`/loans/${l.id}/activate`,{method:'POST',body:{accept_terms:true,simulate_signature:true,simulate_deposit:true},status:409});
 current=await request('/loans/'+l.id);assert.equal(current.status,'in_review');assert.equal(current.contract.mode,'simulation');assert.ok(current.due_at);
 await request(`/loans/${l.id}/progress`,{user:bankers[1],method:'POST',body:{stage:'approved',note:'Invalid banker'},status:403});
 await request(`/loans/${l.id}/progress`,{user:bankers[0],method:'POST',body:{stage:'in_review',note:'Đã kiểm tra tài sản.'}});
 await request(`/loans/${l.id}/progress`,{user:bankers[0],method:'POST',body:{stage:'approved',note:'Đã phê duyệt hồ sơ.'}});
 await request(`/loans/${l.id}/appointment`,{user:bankers[0],method:'POST',body:{scheduled_at:new Date(Date.now()-60000).toISOString(),location:'Phòng giao dịch'},status:400});
 await request(`/loans/${l.id}/appointment`,{user:bankers[0],method:'POST',body:{scheduled_at:new Date(Date.now()+86400000).toISOString(),location:'Phòng giao dịch mẫu',note:'Mang tài liệu'}});
 await request(`/loans/${l.id}/disburse`,{user:bankers[0],method:'POST',body:{confirm:true},status:409});
 await request(`/loans/${l.id}/confirm-appointment`,{method:'POST',body:{}});
 await request(`/loans/${l.id}/disburse`,{user:bankers[0],method:'POST',body:{confirm:true}});
 await request(`/loans/${l.id}/cancel`,{method:'POST',body:{reason:'Too late'},status:409});
 current=await request(`/loans/${l.id}/complete`,{method:'POST',body:{confirm_received:true,simulate_payment:true}});
 assert.equal(current.status,'completed');assert.ok(current.progress.some(p=>p.note==='Đã kiểm tra tài sản.'));
 const ledger=db.prepare('SELECT * FROM ledger WHERE loan_id=?').all(l.id);assert.equal(ledger.filter(e=>e.kind==='service_fee').length,1);assert.equal(ledger.find(e=>e.kind==='service_fee').amount,15000000);assert.ok(ledger.filter(e=>e.kind.includes('deposit')).every(e=>e.state==='refunded_simulated'));
 await request(`/loans/${l.id}/complete`,{method:'POST',body:{confirm_received:true,simulate_payment:true},status:409});
});
test('cancellation reserves the decision for admin and records an auditable settlement',async()=>{const l=await newLoan(),bar=byRole('BAR');await request(`/loans/${l.id}/proposals`,{user:bar,method:'POST',body:proposalData,status:201});await request(`/loans/${l.id}/cancel`,{method:'POST',body:{reason:'Thay đổi kế hoạch'}});const entry=db.prepare('SELECT * FROM ledger WHERE loan_id=?').get(l.id);assert.equal(entry.state,'review_required');await request(`/admin/ledger/${entry.id}/resolve`,{user:bar,method:'POST',body:{outcome:'forfeited_simulated',reason:'Invalid role'},status:403});await request(`/admin/ledger/${entry.id}/resolve`,{user:byRole('ADMIN'),method:'POST',body:{outcome:'refunded_simulated',reason:'Hoàn cọc theo thỏa thuận'}});assert.equal(db.prepare('SELECT state FROM ledger WHERE id=?').get(entry.id).state,'refunded_simulated');assert.ok(db.prepare("SELECT * FROM audit WHERE action='deposit_resolved' AND loan_id=?").get(l.id));});
test('broker can submit on behalf of a personal borrower with consent',async()=>{const l=await request('/loans',{user:byRole('BRO'),method:'POST',body:{...loanData,borrower_type:'PER'},status:201});assert.match(l.alias,/^BRO-/);assert.equal(l.borrower_type,'PER');});
test('banker products persist and borrower cannot create a product',async()=>{const body={title:'Gói vay kiểm thử',borrower_type:'COM',rate:8,max_amount:5000000000,term:36,description:'Điều kiện mẫu'};const p=await request('/products',{user:byRole('BAR'),method:'POST',body,status:201});assert.ok((await request('/products')).some(v=>v.id===p.id));await request('/products',{method:'POST',body,status:403});});
test('notifications are scoped to identity and read state persists',async()=>{const n=await request('/notifications');assert.ok(n.length);assert.ok(n.every(v=>v.user_id===byRole('COM').id));await request('/notifications/read',{method:'POST',body:{}});assert.ok((await request('/notifications')).every(v=>v.read===1));});
test('transaction rollback and disk persistence are real',()=>{const path=join(dir,'persistence.sqlite');const first=createDatabase(path);const u=createUser(first,'COM');assert.throws(()=>transaction(first,()=>{createUser(first,'BAR');throw new Error('rollback');}));assert.equal(first.prepare('SELECT count(*) AS n FROM users').get().n,1);first.close();const restored=createDatabase(path);assert.equal(restored.prepare('SELECT alias FROM users WHERE id=?').get(u.id).alias,u.alias);restored.close();});
test('production financial mode refuses to start until live providers are implemented',()=>{assert.throws(()=>createApp(db,{uploadDir:join(dir,'refused'),demoMode:false}),/DEMO_MODE=true/);});
